# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 197018333c84cd98760166c246038a8d3638e7405b9e6f74e580ab0e0f5b0a03a9ebbc048b6be1592aaa38dac7e063ab077fcc5a787041be62f70710ee00d1ba

test:
  secret_key_base: ef8b5fc192533aaa1fca307a99c671e9472221b42043c6b97b008fdb06837e1abc0739c55ccd1844eca1922c6c2cb736bbc7aa9f19e5b6f83a8a6a556f2a2ad7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
