denver_office = Office.find_or_create_by(name: 'Denver')
new_york_office = Office.find_or_create_by(name: 'New York')
omaha_office = Office.find_or_create_by(name: 'Omaha')
london_office = Office.find_or_create_by(name: 'London')
dublin_office = Office.find_or_create_by(name: 'Dublin')
bangalore_office = Office.find_or_create_by(name: 'Bangalore')

omaha_office.workers << Worker.find_or_create_by(name: 'Andy')

denver_office.workers << Worker.find_or_create_by(name: 'Lizzie')
denver_office.workers << Worker.find_or_create_by(name: 'Ben')
denver_office.workers << Worker.find_or_create_by(name: 'Hap')
denver_office.workers << Worker.find_or_create_by(name: 'Emily')
denver_office.workers << Worker.find_or_create_by(name: 'Katie')
denver_office.workers << Worker.find_or_create_by(name: 'Paul')
denver_office.workers << Worker.find_or_create_by(name: 'Mike')
denver_office.workers << Worker.find_or_create_by(name: 'Dirk')
denver_office.workers << Worker.find_or_create_by(name: 'Robyn')

new_york_office.workers << Worker.find_or_create_by(name: 'Itamar')
new_york_office.workers << Worker.find_or_create_by(name: 'Tiani')
new_york_office.workers << Worker.find_or_create_by(name: 'Peter')
new_york_office.workers << Worker.find_or_create_by(name: 'Zac')
new_york_office.workers << Worker.find_or_create_by(name: 'David')
new_york_office.workers << Worker.find_or_create_by(name: 'Alex')
new_york_office.workers << Worker.find_or_create_by(name: 'Andrew')
new_york_office.workers << Worker.find_or_create_by(name: 'George')
new_york_office.workers << Worker.find_or_create_by(name: 'Chris')
