---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600 autoremove=yes

  - name: Install needed packages for the app
    apt: pkg={{item}} state=installed autoremove=yes
    with_items:
      - software-properties-common
      - build-essential
      - nginx

  - name: Add RAILS env variable
    lineinfile: dest=/etc/environment line={{item}} insertafter='EOF' state=present create=yes
    with_items:
      - "RAILS_ENV={{rails_env}}"
      - "SECRET_KEY_BASE={{rails_secret_token}}"

  - name: Remove nginx default conf
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Copy nginx conf file to available
    template: src=nginx.conf dest=/etc/nginx/sites-available/02-{{appname}}.conf owner={{user}}

  - name: Symlink it to enabled
    file: src=/etc/nginx/sites-available/02-{{appname}}.conf dest=/etc/nginx/sites-enabled/02-{{appname}}.conf state=link

  - name: User group operations
    file: path=/home/{{user}}/{{appname}} group=www-data recurse=true
    become: true

  - name: Add www-data to deploy group
    command: usermod -a -G www-data {{user}}
    become: true
